### ISSUE TITLE
How to train cross-encoder teacher models?

### ISSUE THREAD

**Issue by rogerdehe** [princeton-nlp/DensePhrases#10]
It seems that I cannot find the code to train the cross-encoder teacher models, such as 

    spanbert-base-cased-nq
    spanbert-base-cased-sqdnq
    spanbert-base-cased-squad

Can you tell me how to train these model If I change the train data?

**Comment by jhyuklee** [comment]
Hi, we used [this script](https://github.com/huggingface/transformers/blob/v2.9.0/examples/question-answering/run_squad.py) to train the cross encoder models. We are planning to update the code with this file, soon. Thank you.
