### ISSUE TITLE
Question about faiss parameter

### ISSUE THREAD

**Issue by PlusRoss** [princeton-nlp/DensePhrases#19]
Hi,

Thanks for the amazing work! May I ask how do you choose the parameter for faiss index? Like the number of clusters and quant type OPQ96? It seems that the number of clusters varies with the number of phrases to save.

Thanks!

**Comment by jhyuklee** [comment]
Hi,

In Makefile, you can see the following lines for the faiss parameters:
https://github.com/princeton-nlp/DensePhrases/blob/a64414f8903e58fb29ffba6fe7afdd448025a447/Makefile#L62-L74

The number of clusters depends on the size of your phrase index to build and I recommend reading this part:
https://github.com/princeton-nlp/DensePhrases/tree/main/examples/create-custom-index#building-a-phrase-index

**Comment by PlusRoss** [comment]
Hi,

Thanks for the quick reply! For the number of clusters I see the line:
```
num_clusters: Set to make the number of vectors per cluster < 2000
```
However this still seems to be a large range for this parameter. Are there any other guidelines to narrow it down considering both efficiency and effectiveness?

Thanks.

**Comment by PlusRoss** [comment]
Hi, 

I see. Thanks a lot for your explanation!
