### ISSUE TITLE
Iterative retrieval in case of non-unique top-k retrieval

### ISSUE THREAD

**Issue by dhdhagar** [princeton-nlp/DensePhrases#25]
Hi! Thanks for this amazing work, and for making your code open-source. 

I'm trying to figure out where in the code is non-unique passage retrieval handled that ensures that the final `k` results are unique. According to this footnote on page 3 in your paper "Phrase Retrieval Learns Passage Retrieval, Too", it seems that you perform iterative retrieval to achieve this. Could you point me to the code where this is happening?

<img width="350" alt="image" src="https://user-images.githubusercontent.com/9510980/162666335-7d840fd6-7549-40ad-86b1-03b74426c2cd.png">

**Comment by jhyuklee** [comment]
Hi @dhdhagar! Thanks for your issue.

In this makefile line:
https://github.com/princeton-nlp/DensePhrases/blob/3a0365ef5c3c047b32772fcd18afdb51f161ea7f/Makefile#L490
you can see that we are retrieving top 200 phrases first. And the aggregation based on the unique passages happen here:

https://github.com/princeton-nlp/DensePhrases/blob/main/densephrases/index.py#L430

For our current datasets provided, this is enough to ensure outputting 100 passages per query. There are a very small number of edge cases where top 100 passages are not retrieved even with this setting, and you can enlarge the top-k to 400 in the makefile. Currently there's no automatic procedure for this.

**Comment by dhdhagar** [comment]
That makes it clear, thank you! So, `--top_k` is used to fetch a larger number of phrases, and the length of the final results depends on `--psg_top_k`.
