### ISSUE TITLE
Where is the code for queries to get phrases searching score rank?

### ISSUE THREAD

**Issue by zhaozhengyu0328** [princeton-nlp/DensePhrases#27]
Nice to meet you , I am a newcomer to NLP and I am very intersted in your code , but I am not good at coding ,I havd tried a week to find the code where to get the score of query embedding and the phrases embedding , I have found many score but do not know which is I need .
I would appreciate it if you could answer this question，thanks for your time !
[eval_phrase_retrieval.zip](https://github.com/princeton-nlp/DensePhrases/files/8974707/eval_phrase_retrieval.zip)
[eval_phrase_retrieval.zip](https://github.com/princeton-nlp/DensePhrases/files/8974708/eval_phrase_retrieval.zip)

**Comment by jhyuklee** [comment]
Hi @zhaozhengyu0328,
I guess you are searching for this code: https://github.com/princeton-nlp/DensePhrases/blob/9583883ea9390b0308e806c3e72fa5831afa445b/densephrases/index.py#L189-L218

**Comment by zhaozhengyu0328** [comment]
@jhyuklee thank you !
