### ISSUE TITLE
Missing files for preprocessing natural questions 

### ISSUE THREAD

**Issue by HenryZhou7** [princeton-nlp/DensePhrases#5]
Hi, 

I am trying to make the dataset for natural questions. There seems to be a file missing according to the Makefile.
Is there any plan to including the file as another release?

Missing file `scripts/preprocess/create_nq_reader.py`
`https://github.com/princeton-nlp/DensePhrases/blob/main/Makefile#L384`

**Comment by jhyuklee** [comment]
@mjeensung Do you have this file? I think I omitted this.

**Comment by jhyuklee** [comment]
Hi @HenryZhou7, we added two missing files: https://github.com/princeton-nlp/DensePhrases/pull/6

By the way, the NQ pre-processing was done very long time ago and the documentation is not good. We also used https://github.com/AkariAsai/learning_to_retrieve_reasoning_paths in our training set, so check it out.
