### ISSUE TITLE
Missing files for preprocessing Wikipedia

### ISSUE THREAD

**Issue by jplu** [princeton-nlp/DensePhrases#7]
Hi!

First of all thanks a lot for this amazing project!!

When going through the repo I have noticed some missing scripts in the `scripts\preprocess` folder. Namely:

- `build_db.py`
- `prep_wikipedia.py`
- `build_wikisquad.py`

Thanks in advance :)

**Comment by jhyuklee** [comment]
Thanks for letting us know! I think @mjeensung can add those files as well?
